### ISSUE TITLE
feature request continue running tgcf past mode skip errors

### ISSUE THREAD

**Issue by ankit-sinha-18** [aahnik/tgcf#50] opened 2021-04-11 02:19 UTC
![Capture](https://user-images.githubusercontent.com/72637068/114290055-59f80680-9a9a-11eb-963f-1beee96c6acb.JPG)

how to fix this issue?

**Comment by aahnik** [comment] 2021-04-11 02:26
@ankit-sinha-18, you created a good issue. I never noticed this before. Hopefully, this will be fixed in the next release. read #43

**Comment by ankit-sinha-18** [comment] 2021-04-11 02:38
Okay, Thank you...

I have a doubt,
Can't poll be forwarded without forward tag?
because,I have used unofficial version of telegram like plus messenger,telegraph,bgram..
In All these apps,when forwarding poll without quotes,It gets forwarded with quotes automatcally.

**Comment by aahnik** [comment] 2021-05-05 14:08
@ankit-sinha-18  does this error still occur? the screenshot you showed is of the old version. 

please try again with a new version

**Comment by aahnik** [comment] 2021-05-05 14:08
> Can't poll / Quiz be forwarded without forward tag?
> because,I have used unofficial version of telegram like plus messenger,telegraph,bgram..
> In All these apps,when forwarding poll / Quiz without quotes,It gets forwarded with quotes automatically.

i cant understand. please show a screenshot for this.

**Comment by aahnik** [comment] 2021-05-05 14:16
@ankit-sinha-18,  I tested with the new version, and this error does not occur anymore.

after the major release of tgcf 0.1.17, this issue is solved, due to a deep change in how tgcf works.

**Comment by ankit-sinha-18** [comment] 2021-05-05 14:47
![Screenshot_2021_0505_201448](https://user-images.githubusercontent.com/72637068/117160348-aa832b00-adde-11eb-8f23-7371eda6eb43.png)


This error occurred again in tgcf new version.

You can check it's version,it is 0.1.27

**Comment by aahnik** [comment] 2021-05-05 14:51
please don't use screenshots, copy and paste the error message, and update your above comment.

are you using termux? 

the poll object forwarding is happening smoothly in my computer. need to check for termux.

**Comment by ankit-sinha-18** [comment] 2021-05-05 15:11
Yes,I am using it in termux

Error:-

ERROR:root:Cannot use <telethon.tl.types.MessageMediaPoll object at 0x713713a700> as file
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tgcf/past.py", line 32, in forward_job
    await send_message(client, destination, message)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tgcf/utils.py", line 8, in send_message
    return await client.send_message(*args)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/messages.py", line 782, in send_message
    return await self.send_file(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/uploads.py", line 386, in send_file
    raise TypeError('Cannot use {!r} as file'.format(file))
TypeError: Cannot use <telethon.tl.types.MessageMediaPoll object at 0x713713a700> as file
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.175.59:443/TcpFull...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.175.59:443/TcpFull complete!

**Comment by ankit-sinha-18** [comment] 2021-05-05 16:23
I got the same error in Heroku

> ERROR:root:Cannot use <telethon.tl.types.MessageMediaPoll object at 0x7f1df78e0f10> as file

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/tgcf/past.py", line 34, in forward_job
    await send_message(client, destination, message)
  File "/app/.heroku/python/lib/python3.9/site-packages/tgcf/utils.py", line 8, in send_message
    return await client.send_message(*args)
  File "/app/.heroku/python/lib/python3.9/site-packages/telethon/client/messages.py", line 782, in send_message
    return await self.send_file(
  File "/app/.heroku/python/lib/python3.9/site-packages/telethon/client/uploads.py", line 386, in send_file
    raise TypeError('Cannot use {!r} as file'.format(file))
TypeError: Cannot use <telethon.tl.types.MessageMediaPoll object at 0x7f1df78e0f10> as file
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.175.59:443/TcpFull...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.175.59:443/TcpFull complete!

**Comment by aahnik** [comment] 2021-05-08 05:29
hi @ankit-sinha-18 , did you use official app to create the poll ? i could not reproduce this error.

try creating the poll with official app.

and what have you set to `show_forwarded_from` ? please show me your config file.

**Comment by ankit-sinha-18** [comment] 2021-05-08 05:39
As you can see ,that error is
`ERROR:root:Cannot use <telethon.tl.types.MessageMediaPoll object at 0x7f1df78e0f10> as file`

But ,in actual **that is not Poll** ,that is **quiz**.
When using `tgcf` in `past` mode,it couldn't forward quiz object
And program crashed at that time,

You can reproduce this error , make a quiz in from Channel and try to forward in another channel,you will get same error message, which I am getting.

**Comment by aahnik** [comment] 2021-05-08 06:28
a quiz is a poll in quiz mode.

and after turning quiz mode on, I was able to reproduce the error. I cant do anything about it, because it is problem with telethon.

but what I can do, is prevent the stopping of script. it will show an error on terminal, and then continue with next message.

this error occurs for both past and live mode

**Comment by ankit-sinha-18** [comment] 2021-05-08 06:37
Yes, similar problem occurs in pyrogram also.
Quiz is forwarded as copy in pyrogram but it becomes Poll when it is copied. So this is another type of problem in pyrogram also.

Yes,you can do something to prevent the stopping of script and skip the quiz object

**Closed** 2021-05-08 06:47 UTC

**Comment by aahnik** [comment] 2021-05-08 09:36
Hi @ankit-sinha-18 , try forwarding quiz poll, with show_forwarded_from set to true.

(Read wiki)

Then it is supposed to work.

Try and tell me.

**Comment by ankit-sinha-18** [comment] 2021-05-08 10:22
But I don't need quiz as forwarded tag, I want them as a copy.
I know,It is not going to be forwarded without quote..

So, setting `show_forwarded_from` true is the only way to bypass error in tgcf!!?
